name: 'Generic Workflow Builder'
description: 'A custom GitHub actions pipeline that wrappedup build, unit_test, benchmark and extract stages'
  
inputs:
  module_name:
    description: 'Name of the module'
    required: true
  openfhe_development_branch:
    description: 'openfhe-development branch for testing'
    required: true
  cmake_args_openfhe_lib:
    description: 'Argument for cmake command'
    required: true

runs:
  using: "composite"
  steps:
    #####################################################################################
    - name: '${{ inputs.module_name }}_print_input'
      shell: bash
      run: |
        # pwd
        echo "======> step ${{ inputs.module_name }}_print_input"

        # Debugging use only
        echo "Input values:
        module_name=${{inputs.module_name}}
        openfhe_development_branch=${{inputs.openfhe_development_branch}}
        cmake_args_openfhe_lib=${{inputs.cmake_args_openfhe_lib}}
        "
    #####################################################################################
    - name: '${{ inputs.module_name }}_cleanup'
      shell: bash
      run: |
        # pwd
        echo "======> step ${{ inputs.module_name }}_cleanup"

        #### Uninstall openfhe by simply deleting $OPENFHE_PACKAGER_DIR along with
        #### the local virtual python environment which has openfhe installed

        ### openfhe-python-packager location
        OPENFHE_PACKAGER_DIR="$PWD/openfhe-python-packager"
        echo "OPENFHE_PACKAGER_DIR=$OPENFHE_PACKAGER_DIR"
        echo "OPENFHE_PACKAGER_DIR=$OPENFHE_PACKAGER_DIR" >> $GITHUB_ENV
        if [ -d "$OPENFHE_PACKAGER_DIR" ]; then
          rm -Rf $OPENFHE_PACKAGER_DIR;
        fi

    #####################################################################################
    - name: '${{ inputs.module_name }}_build_openfhe'
      shell: bash
      run: |
        # pwd
        echo "======> step ${{ inputs.module_name }}_build_openfhe"
        
        git clone https://github.com/openfheorg/openfhe-python-packager.git
        cd $OPENFHE_PACKAGER_DIR

        # update ci-vars.sh:
        sed -i \
            -e "s|^OPENFHE_TAG=.*|OPENFHE_TAG=${{inputs.openfhe_development_branch}}|"           \
            -e "s|^OPENFHE_PYTHON_TAG=.*|OPENFHE_PYTHON_TAG=${{inputs.openfhe_python_branch}}|"  \
            -e "s|^ADDL_CMAKE_FLAGS=.*|ADDL_CMAKE_FLAGS=\"${{inputs.cmake_args_openfhe_lib}}\"|" \
            ./ci-vars.sh

        echo "====== ci-vars.sh ======"
        cat ./ci-vars.sh
        echo "========================"

        ./build_openfhe_wheel.sh

    #####################################################################################
    - name: '${{ inputs.module_name }}_tests'
      shell: bash
      run: |
        # pwd
        echo "======> step ${{ inputs.module_name }}_tests"

        ### save openfhe_python location before we start the process
        OPENFHE_DIR="$PWD"
        # echo "OPENFHE_DIR=$OPENFHE_DIR"
 
        cd $OPENFHE_PACKAGER_DIR

        ### activate the virtual environment
        source ./scripts/get-env.sh

        ### install the wheel
        pip install ./build/dist/*.whl

        echo "====== Currently installed OPENFHE packages ======"
        pip list|grep openfhe
        echo "=================================================="

        ### run tests from the main openfhe_python location
        cd $OPENFHE_DIR/tests
        pytest --run-all

        ### deactivate the virtual environment
        deactivate

    # #####################################################################################
    # - name: '${{ inputs.module_name }}_final_cleanup'
    #   shell: bash
    #   run: |
    #     pwd
    #     rm -rf ${OPENFHE_PACKAGER_DIR}
